---
- name: "Ensure that ssh_user value is defined"
  ansible.builtin.assert:
    that:
      - ssh_user is defined
    fail_msg: "ssh_user variable is not defined. Unable to continue"
    success_msg: "ssh_user variable is defined as {{ ssh_user }}"

- name: "Configure SSH"
  ansible.builtin.import_tasks:
    file: ssh.yml
...
